#!/usr/bin/bash

for CHRNUMBER in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y M
do
	CHR="chr$CHRNUMBER"
	echo $CHR
	FNAME=$CHR"_exons.gtf"
	echo $FNAME
	grep $CHR gencode.v14.annotation.gtf > $FNAME
done
